### ISSUE TITLE
Easy Mojang Auth Bypass

### ISSUE THREAD

**Issue by ghost** [HackerYijia/Projectcraft#2]
All you need to do in order to bypass is go to [INSERT THE CLIENT ADDRESS HERE]/projectcraft.html.
the best way to fix this would be to implement a check to see if it's in an iframe, and if its not, refuse to boot the client.

**Comment by HackerYijia** [comment]
Thanks.
To be honest I kind of allowed that happen because... You know....
(ignore that)
Since you mentioned it I will fix it by adding an X-Real-IP header.
